### PR TITLE
Move Plugins to seperate repos

### PR DESCRIPTION
**Pull request by drapergeek**
@ttscoff, this was my first attempt at moving over the plugins. This is in reference to https://github.com/ttscoff/Slogger/issues/271

I have set them up in repos here: https://github.com/sloggerplugins and I'd be happy to transfer that org over to you. I also have a quick script to create the repos on github and upload them if you'd prefer to just keep them on your own account. I have no opinion I just needed something to get it working!

At this point you can install a plugin using `rake plugin:install[feed]`. You can also `rake plugin:enable[feed]` or `rake plugin:disable[feed]`. 

The plugins and plugins_disabled directories are ignored. The rake task will create a slogger_plugins directory at the same level as the slogger directory, git clone down the plugin and then symlink over the plugin. This should make it easy for users to modify or update individual plugins easily. We could also easily add a `plugins:update[feed]` and `plugins:update[all]` command to make upgrading those easier.

Would love to get any initial feedback on this implementation.

### CODE REVIEW

**Comment by mrjcleaver** [comment]
I was just thinking the same about getting plugins in separate repos. I'm putting together a plugin myself and want to find and document issues about the core without having to wade through issues related to plugins that I have no interest in.

**Comment by mrjcleaver** [comment]
Well, it just took me 15 minutes to review the changes. They are straightforward. 

A bigger question is whether we can move bug tracker issues relating to plugins to the other repo.

As most issues relate to plugins maybe it's better to move the core out.

**Comment by mrjcleaver** [comment]
Another advantage of separate repos is that plugins can have their own Gemfiles - in turn that avoids breadking the out of the box install because one thing needs ImageMagick https://github.com/ttscoff/Slogger/issues/344 or another has decided to add  'active_support/time'

**Comment by drallgood** [comment]
I agree. 
It would also make the whole process of installing plugins easier. All you need to do is add them to the Gemfile

**Comment by coopermj** [comment]
Separate Gemfiles would be great. When you’re adding ImageMagick, there’s no clean way to make it easy for others to add it.

While you’re looking at that, though, I’ve had trouble with gems not being part of launchd’s path. Creating a shell script that adds the relevant paths fixes the issue, but doesn’t seem very robust.

On Jan 25, 2015, at 7:27 AM, Martin Cleaver <notifications@github.com<mailto:notifications@github.com>> wrote:


Another advantage of separate repos is that plugins can have their own Gemfiles - in turn that avoids breadking the out of the box install because one thing needs ImageMagick #344<https://github.com/ttscoff/Slogger/issues/344> or another has decided to add 'active_support/time'

**Comment by ttscoff** [comment]
If you're using multiple gemsets, create a wrapper for Slogger with your 
Ruby version manager.

**Comment by mrjcleaver** [comment]
Re separating issues:
- move plugin issues out
- move core issues out and rename to preserve original semantics

https://github.com/holman/feedback/issues/413 talks about moving issues ad provides a couple of tools.

**Comment by mrjcleaver** [comment]
Notably https://github.com/google/github-issue-mover , a tool written by Google.

**Comment by ttscoff** [comment]
Let's get this done. I'm willing to give @mrjcleaver and @drapergeek full push access to this repo if you want to do final tests in a branch and merge to master when ready (rebasing the develop branch). I can also set up a slogger_plugins repo on my account and add you to that, too. You guys have time?

**Comment by drapergeek** [comment]
@ttscoff I have no idea if this is working or not anymore. I can take some time next week and pull it apart.

This design was actually based on a new org that I set up. Each plugin would then go into a repo of it's own instead of having one "plugins" repo. If that's OK and you're still interested I'd be happy to work with @mrjcleaver on this, I'm definitely still interested in having this setup.

**Comment by ttscoff** [comment]
Absolutely.

**Comment by mrjcleaver** [comment]
I agree one-repo per plugin is best.

Last I tried it your scheme worked well. Given that Brett is okay with the scheme, can you refresh it and I'll help review and chip in?

Looking forward to this!

Best, M.

**Comment by mrjcleaver** [comment]
I've been buried, btw, but should have done time this weekend.

**Comment by mrjcleaver** [comment]
Any luck @drapergeek ?

**Comment by drapergeek** [comment]
@mrjcleaver Sorry, I haven't had time to look at this recently.

Just fired it up and got everything rebased.

The only thing left is that the https://github.com/sloggerplugins org is out of date for all the plugins. I originally wrote a script to create all those repos. If we're going with this solution I'll need to whip that up again and update all those repos since they're majorly out of date.

Before I do that, is this the best solution or the solution we want for now? This will not address the issue of letting individual plugins have their own Gemfile. An alternative solution would be to move each plugin to an actual Gem, just hosted through GitHub instead of forcing a lot of new gems on RubyGems and load them in the Slogger main file. This would in theory make the process of installing and uninstalling a plugin easier for anyone who knows about Ruby.

Thoughts? I have no idea how much time would be involved in that but I'd be up for tackling it if we think that's an easier way. I'm not sure why I didn't try that first.

**Comment by ttscoff** [comment]
I'm good with that plan (GitHub-hosted gems). This is a great move.

It would be awesome (and I'm willing to tackle this part once the new 
setup is in place) if the CLI could enable and disable plugins without 
moving files around, too, eliminating the "plugins_disabled" folder and 
relying on a config file that could be updated programatically. Similar 
to the way that Sublime Text allows you to add a package, but then 
ignore the package without uninstalling.

I could fairly easily make a GUI for that, too, just parsing the YAML 
config into a PLIST and putting a simple Cocoa GUI on it…

-Brett

**Comment by drapergeek** [comment]
:cool: I just started to play with this and I think the gem process will be fairly easy to handle. The worst part will be creating each of the gems. I'm going to spend more time tinkering with this over the weekend.

**Comment by drapergeek** [comment]
Closing this PR in favor of this one: https://github.com/ttscoff/Slogger/pull/382

**Pull request closed without merging**
