### PR TITLE
Don't hardcode ruby binary

### PR DESCRIPTION
**Pull request by stevebutterworth**
Instagram plugin errors in a very confusing way when trying to initially authenticate due to hardcoding of ruby path https://github.com/ttscoff/Slogger/issues/339

### CODE REVIEW

**Comment by ttscoff** [comment]
This is a good change, but any reason not to make it `/usr/bin/env ruby`?

**Comment by stevebutterworth** [comment]
I'm a ruby developer and use RVM to manage my rubies. I think that's why I personally don't have ruby in this path.

**Comment by ttscoff** [comment]
Even if you use RVM, you should never touch the system ruby. RVM won't 
do that by default. Either way, env should pick up whatever you have set 
in your login shell, but Slogger is designed to run on the system ruby 
because if you run it from launchd, it's not loading your bash_profile 
to initiate rvm.

**Comment by stevebutterworth** [comment]
Ah interesting. Guess my system ruby must be somewhere different then. But not something I've ever moved knowingly.

**Comment by ttscoff** [comment]
If you don't have a ruby at /usr/bin/ruby, you should be able to fix the 
issue by symlinking a Ruby 2.0 binary there from one of your rvm rubies. 
E.g. `ln -s ~/.rvm/rubies/ruby-2.0.0-p451/bin/ruby /usr/bin/ruby`. Make 
sure that `bundle install` runs for that one, which should be doable if 
you run `rvm use system` after making the link.

-Brett

**Pull request closed without merging**
