### PR TITLE
instagram plugin using api

### PR DESCRIPTION
**Pull request by rjames86**
Adding Instagram plugin to Slogger.

Advantage over an IFTT rule is that you get:
- Like count
- Who liked your photo
- Comments
- Location, if included (also place name if you used Foursquare)

Timestamps for the post are set as the time the photo was posted, not the time Slogger was run.

Example entry:

I've been using this for about a year now with no issues. The authentication flow is meant to be low effort and opens a local server, which allows the user to then enter their auth key directly in the terminal once they've approved the app.

### CODE REVIEW

**Comment by bleepnik** [comment]
I am stuck on the authentication part and have gone as far as I can with my limited knowledge. The first part works: a web page opens with a "Connect with Instagram" link. However, clicking that link doesn't work, failing to connect to localhost. In Terminal, I see:

```
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/nik/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace
```

Trying to find out what that means led me to:
https://github.com/flori/json/issues/229

From what I can understand, it seems that json has been patched to address the incompatibility with ruby 2.2. I'm using 2.2.3 and still seeing this error. I could use a different version, but I can't figure out which will work.

Is this plugin still working for you? I hate to impose, but if you could provide some guidance, I'd sure appreciate it.

**Comment by rjames86** [comment]
Hey -

Looks like I'm running a bit older version of ruby

    ruby -v
    ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

Looks like @ttscoff has mentioned this [here](https://github.com/ttscoff/Slogger#system-requirements) in his System Requirements. Is there any chance that you could try running it with the default Mac bundled version of Ruby and see if you get the same errors?

**Comment by bleepnik** [comment]
I can't believe I spent so long trying to troubleshoot this and overlooked something so simple, not to mention the very first Troubleshooting paragraph. :disappointed: Thank you, @rjames86, for being so kind about it; it's sorted now, and appears to work perfectly.

**Comment by rjames86** [comment]
Haha - and it gave me an easy out :)  Glad it's working!

**Pull request merged**
